### PR TITLE
WIP OAuth2 Support

### PR DESCRIPTION
**Pull request by bstopp**
## Description

Update API to support OAuth Server-to-Server client credentials approach to Authentication.

## Related Issue

#155 

## Motivation and Context

Updates library to prepare for removal of deprecated JWT solution.

## How Has This Been Tested?

Update existing unit tests, and added new ones.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the [code style](CODE_STYLE.md) of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by rperelma** [comment]
Wow, thank you @bstopp !!!  @francoisledroff  is out this week, but will review when he is back.

**Comment by bstopp** [comment]
@francoisledroff  - I don't know why the integration tests are failing. Its saying NPE, which indicates it can't find the fallback properties file. The actions should have all the necessary properties defined to successfully run these checks.

I don't have the information necessary to run the IT tests offline. I'm not sure if this is something you can do, to check the updates and make sure it wasn't something i introduced?

**Comment by bstopp** [comment]
I went ahead and updated all the plugins and dependencies to latest releases.

I'll be going back and adding more tests over the next couple of days while folks find time to review.

**Comment by francoisledroff** [comment]
@bstopp the IT tests are leveraging GH secrets only available on the main remote repo.
If you push your change against a remote branch and update your PR accordingly, 
the IT test should run (using the  deprecated JWT authentication)

**Pull request closed without merging**
