### PR TITLE
Made the code compatible with java 8

### PR DESCRIPTION
**Pull request by pulguptaAdobe**
## Description

With this change I have made the SDK compatible with java 8 so that it can even work with projects who are stuck on 1.8.

## Related Issue
https://github.com/adobe/aio-lib-java/issues/104

## Motivation and Context
AEM Guides is not yet onJava 11 but needs integration with IO Events. This change will help Guides to use the sdk without being forced to migrate to Java 11.

## How Has This Been Tested?
I tested the changes by deploying my publisher and consumer which were working with java 11 and tested them using the version which was migrated to java 8.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the [code style](CODE_STYLE.md) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by pulguptaAdobe** [comment]
@francoisledroff : Can you please check if we can merge and release this change?

**Review by francoisledroff — CHANGES_REQUESTED** [review]
while this looks ok,
I would like to keep the default artifact baked using java11.
However I'm ok adding a java8 profile and build classifier
see for instance how it was done in https://github.com/adobe/aio-lib-java-cloudmanager  
see https://github.com/adobe/aio-lib-java-cloudmanager/commit/feba9c1178cc6ebe6f21a047579414c77bcf1b5d#diff-6e7d26b133bcd41ab7657c7f6eb31557c3d24c6a41091bb58876d02f2b717277

**Comment by pulguptaAdobe** [comment]
@francoisledroff : even though I have done the java8 integration via a new profile but I have three concerns:

1) It has made the pom scattered with classifiers
2) Maven does not use classifiers while resolving transitive dependencies (tried it) . So users will have exclude all transition dependencies of aio and include them again with classifier sometimes doing that a couple of time [0].
3) We already have a aem65 classifier for aem modules in this sdk. I do not have the complete idea of this existing classifier and now it can impact this new java8 classifier.

[0]

```
         <dependency>
            <groupId>com.adobe.aio</groupId>
            <artifactId>aio-lib-java-events-journal</artifactId>
            <version>0.1.4-SNAPSHOT</version>
            <classifier>java8</classifier>
            <exclusions>
                <exclusion>
                    <groupId>com.adobe.aio</groupId>
                    <artifactId>aio-lib-java-ims</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.adobe.aio</groupId>
                    <artifactId>aio-lib-java-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.adobe.aio</groupId>
            <artifactId>aio-lib-java-ims</artifactId>
            <version>0.1.4-SNAPSHOT</version>
            <classifier>java8</classifier>
            <exclusions>
                <exclusion>
                    <groupId>com.adobe.aio</groupId>
                    <artifactId>aio-lib-java-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.adobe.aio</groupId>
            <artifactId>aio-lib-java-core</artifactId>
            <version>0.1.4-SNAPSHOT</version>
            <classifier>java8</classifier>
        </dependency>
```

**Comment by francoisledroff** [comment]
I see... may be we should just downgrade the java baseline to java8, as you first proposed.
let me sync up with my team...

**Comment by francoisledroff** [comment]
could you re-work your PRs the simple way, a bit like you first did, but publishing the artifact with a `jdk8` classifier, and we'll push the change to a `jdk8` remote branch and release from there ...

**Comment by francoisledroff** [comment]
thanks for your PR @pulguptaAdobe 
I'll merge this into our `java8` remote branch and I'll polish it with another PR (tackling https://github.com/adobe/aio-lib-java/issues/21 ) 
stay tuned.

**Comment by francoisledroff** [comment]
see https://github.com/adobe/aio-lib-java/pull/130

**Pull request merged**
